# Project 5 -- Taylor Saunders

**TA Help:** 
na
    
**Collaboration:** 
na

## Question 1


Write a function called avg_aggreg_temp that takes 5 parameters: the file_location as a string, the column_title_list as a list of column titles, the start_date as an integer, the end_date as an integer, and the temperature element_code as a string, with default value "TAVG". Your function should output the average value for rows with that element_code. For instance, in the default case (where element_code is "TAVG"), your function should output the average value which is the average of the average temperatures (as a decimal number).

Run the function for on the data set 2018.csv, using start_date 20180101 and end_date 20180115, and with "TAVG" as the element_code.

In [3]:
import pandas as pd

Pre-work for the function

In [5]:
myDF = pd.read_csv("/anvil/projects/tdm/data/noaa/1880.csv", header = None, names = ["id","date","element_code","value","mflag","qflag","sflag","obstime"])

In [6]:
myDF.head()

id      date element_code  value mflag qflag sflag  obstime
0  AGE00147705  18800101         PRCP      0   NaN   NaN     E      NaN
1  AGE00147708  18800101         PRCP     36   NaN   NaN     E      NaN
2  AGE00147709  18800101         PRCP     36   NaN   NaN     E      NaN
3  AGE00147712  18800101         PRCP      0   NaN   NaN     E      NaN
4  AGE00147713  18800101         TMAX     52   NaN   NaN     E      NaN

In [12]:
myDF[(myDF['date'] >= 18800701) & (myDF['date'] <= 18800731)].shape

(31676, 8)

In [14]:
myDF.shape

(370779, 8)

In [16]:
myDF[(myDF['date'] >= 18800701) & (myDF['date'] <= 18800731) & (myDF['element_code']=='PRCP')]['value'] .mean()

14.785096332466429

function

function: def avg_aggreg_temp

function parameters: (file_location, column_title_list, start_date, end_date, element_code)

full function:

def avg_aggreg_temp(file_location, column_title_list, start_date, end_date, element_code):

    myDF = pd.read_csv(file_location, header=None, names=column_title_list)
    
    myresult = myDF[(myDF['date'] >= start_date) & (myDF['date'] <= end_date) & (myDF['element_code'] == my_element_code)]['value'].mean()
    
    return myresult


In [33]:
def avg_aggreg_temp(file_location, column_title_list, start_date, end_date, element_code):
    """
    file_location: LOCATION OF THE FILE WHERE DATA IS STORED
    column_title_list: CONTAINS NAMES OF THE COLUMNS
    start_date: FIRST WE WANT TO ANALYZE
    end_date: LAST WE WANT TO ANALYZE
    element_code: TYPE OF DATA TO CONSIDER IN THE ANALYSIS
    
    returns: FLOATING POINT VALUE CONTAINING THE AVERAGE OF THE VALUES FOR THE ROWS CORRESPONDING TO THE ELEMENT_CODE ROWS
    """
    myDF = pd.read_csv(file_location, header=None, names=column_title_list)
    myresult = myDF[(myDF['date'] >= start_date) & (myDF['date'] <= end_date) & (myDF['element_code'] == element_code)]['value'].mean()
    return myresult

In [ ]:
avg_aggreg_temp("/anvil/projects/tdm/data/noaa/1880.csv", ["id","date","element_code","value","mflag","qflag","sflag","obstime"], 18800701, 18800731, 'PRCP')

In [32]:
avg_aggreg_temp("/anvil/projects/tdm/data/noaa/1880.csv", ["id","date","element_code","value","mflag","qflag","sflag","obstime"], 18800701, 18800731, 'TAVG')

235.09677419354838

In [ ]:
avg_aggreg_temp("/anvil/projects/tdm/data/noaa/2018.csv", ["id","date","element_code","value","mflag","qflag","sflag","obstime"], 20180101, 20180115, 'TAVG')

## Question 2

Create a function that takes a list of years (or, if you prefer, a list of file locations), as a list of column names, and an element_code as input, and returns a dictionary with one entry per year. In the dictionary, for each year, it should have the year as the key and the average value of the specified element_code as the value for that year.

Test your function for the element_code "TAVG" and for the range of four years 1880 to 1883 (inclusive), i.e., range(1880,1884).

In [5]:
column_title_list = ["id","date","element_code","value","mflag","qflag","sflag","obstime"]
myyear = 1880
file_location = f'/anvil/projects/tdm/data/noaa/{myyear}.csv'

myDF = pd.read_csv(file_location, header=None, names=column_title_list)
element_code = 'PRCP'

In [8]:
myresult = myDF[(myDF['element_code'] == element_code)]['value'].mean()
print(myresult)

17.528739659455965


In [21]:
def avg_aggreg_temp_by_year(range_of_years, column_title_list, element_code = 'TAVG') -> dict:
    """
    range_of_years: LIST OF YEARS OF DATA WE ARE ANALYZING
    column_title_list: CONTAINS NAMES OF THE COLUMNS
    element_code: TYPE OF DATA TO CONSIDER IN THE ANALYSIS
    
    returns: A DICTIONARY FOR ONE FLOATING POINT VALUE FOR EACH YEAR CONTAINING THE AVERAGE OF THE VALUES FOR THE ROWS CORRESPONDING TO THE ELEMENT_CODE ROWS
    """
    mydict = {}
    for myyear in range_of_years:
        file_location = f'/anvil/projects/tdm/data/noaa/{myyear}.csv'
        myDF = pd.read_csv(file_location, header=None, names=column_title_list)
        myresult = myDF[(myDF['element_code'] == element_code)]['value'].mean()
        mydict[myyear] = myresult
    return mydict

In [22]:
avg_aggreg_temp_by_year(range(1880,1884), ["id","date","element_code","value","mflag","qflag","sflag","obstime"], "TAVG")

{1880: 127.30054644808743,
 1881: 49.00669116954104,
 1882: 58.33541290428501,
 1883: 50.54050116550116}

## Question 3

Modify the function that you created in Question 2, to include an extra parameter for the month. This function should have the same behavior as in Question 2, but for each year, the function should only use the data from that month of the year.

Test your function for the element_code "TAVG" and for the range of four years 1880 to 1883 (inclusive), i.e., range(1880,1884), and for the month August in each year.

In [32]:
def avg_aggreg_temp_by_year_and_month(range_of_years, mymonth, column_title_list, element_code = 'TAVG') -> dict:
    """
    range_of_years: LIST OF YEARS OF DATA WE ARE ANALYZING
    column_title_list: CONTAINS NAMES OF THE COLUMNS
    mymonth: ONLY MONTH OF DATA
    element_code: TYPE OF DATA TO CONSIDER IN THE ANALYSIS
    
    returns: A DICTIONARY FOR ONE FLOATING POINT VALUE FOR EACH YEAR CONTAINING THE AVERAGE OF THE VALUES FOR THE ROWS CORRESPONDING TO THE ELEMENT_CODE ROWS
    """
    mydict = {}
    for myyear in range_of_years:
        file_location = f'/anvil/projects/tdm/data/noaa/{myyear}.csv'
        myDF = pd.read_csv(file_location, header=None, names=column_title_list)
        myDF['month'] = pd.to_datetime(myDF['date'], format = '%Y%m%d').dt.month
        myresult = myDF[(myDF['element_code'] == element_code) & (myDF['month'] == mymonth)]['value'].mean()
        mydict[myyear] = myresult
    return mydict

In [34]:
avg_aggreg_temp_by_year_and_month(range(1880,1884), 8, ["id","date","element_code","value","mflag","qflag","sflag","obstime"])

{1880: 225.70967741935485,
 1881: 188.42227122381476,
 1882: 207.34585741811176,
 1883: 185.22810060711188}

## Question 4

Create a function that takes a list of years as input, and identifies the year that has the most qflags of the type that the user specified.

Run the function for years in the range 1880 to 1883, and test it with some various qflag values, such as D, G, I, K, L, N, O, S, X.

In [55]:
def year_max_qflag(range_of_years, column_title_list, qflag) -> dict:
    """
    range_of_years: RANGE USER DESIRES FOR ANALYSIS
    
    column_title_list: CONTAINS NAMES OF THE COLUMNS
    
    qflag: SPECIFIED Q FLAG FOR ANALYSIS
    """
    qflagdict = {}
    for year in range_of_years:
        file_location = f'/anvil/projects/tdm/data/noaa/{myyear}.csv'
        myDF = pd.read_csv(file_location, header=None, names=column_title_list)
        myqflag = myDF[myDF['qflag'] == qflag].shape[0]
        qflagdict[year] = myqflag
    return qflagdict

In [40]:
year_max_qflag(range(1880, 1884), ["id","date","element_code","value","mflag","qflag","sflag","obstime"], "D") 

{1880: 548, 1881: 548, 1882: 548, 1883: 548}

In [43]:
year_max_qflag(range(1880, 1884), ["id","date","element_code","value","mflag","qflag","sflag","obstime"], "G")

{1880: 1, 1881: 1, 1882: 1, 1883: 1}

In [44]:
year_max_qflag(range(1880, 1884), ["id","date","element_code","value","mflag","qflag","sflag","obstime"], "I")

{1880: 363, 1881: 363, 1882: 363, 1883: 363}

In [46]:
year_max_qflag(range(1880, 1884), ["id","date","element_code","value","mflag","qflag","sflag","obstime"], "K")

{1880: 0, 1881: 0, 1882: 0, 1883: 0}

In [48]:
year_max_qflag(range(1880, 1884), ["id","date","element_code","value","mflag","qflag","sflag","obstime"], "L")

{1880: 0, 1881: 0, 1882: 0, 1883: 0}

In [50]:
year_max_qflag(range(1880, 1884), ["id","date","element_code","value","mflag","qflag","sflag","obstime"], "N")

{1880: 12, 1881: 12, 1882: 12, 1883: 12}

In [51]:
year_max_qflag(range(1880, 1884), ["id","date","element_code","value","mflag","qflag","sflag","obstime"], "O")

{1880: 3, 1881: 3, 1882: 3, 1883: 3}

In [52]:
year_max_qflag(range(1880, 1884), ["id","date","element_code","value","mflag","qflag","sflag","obstime"], "S")

{1880: 6, 1881: 6, 1882: 6, 1883: 6}

In [53]:
year_max_qflag(range(1880, 1884), ["id","date","element_code","value","mflag","qflag","sflag","obstime"], "X")

{1880: 3, 1881: 3, 1882: 3, 1883: 3}

## Question 5

Explore the dataset files from the noaa directory, and create a function of your own design, about something that interests you. Make sure to include a docstring that explains the function’s definition.

Run your function, and explain the inputs and outputs, so that a user can understand how it works

In [56]:
myDF.columns

Index(['id', 'date', 'element_code', 'value', 'mflag', 'qflag', 'sflag',
       'obstime'],
      dtype='object')

In [57]:
def year_max_qflag(range_of_years, column_title_list, mflag) -> dict:
    """
    range_of_years: RANGE USER DESIRES FOR ANALYSIS
    
    column_title_list: CONTAINS NAMES OF THE COLUMNS
    
    qflag: SPECIFIED Q FLAG FOR ANALYSIS
    """
    qflagdict = {}
    for year in range_of_years:
        file_location = f'/anvil/projects/tdm/data/noaa/{myyear}.csv'
        myDF = pd.read_csv(file_location, header=None, names=column_title_list)
        myqflag = myDF[myDF['qflag'] == qflag].shape[0]
        qflagdict[year] = myqflag
    return qflagdict

## Pledge

By submitting this work I hereby pledge that this is my own, personal work. I've acknowledged in the designated place at the top of this file all sources that I used to complete said work, including but not limited to: online resources, books, and electronic communications. I've noted all collaboration with fellow students and/or TA's. I did not copy or plagiarize another's work.

> As a Boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together – We are Purdue.